version: '3.9'

services:
  web:
    build:
      context: ./web/
      dockerfile: Dockerfile
    ports:
      - 3080:80
      - 3443:443
    volumes:
      - ./web/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web/certs/:/etc/certs/
  db:
    build:
      context: ./db/
      dockerfile: Dockerfile
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis:7.0
    ports:
      - 6379:6379
    volumes:
      - ./tmp/redis:/data
    command: redis-server --appendonly yes

  api:
    tty: true
    depends_on:
      - db
      - redis
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
    command: bash -c "rm -f tmp/pids/server.pid & bundle exec rails s -p 3000 -b '0.0.0.0'"

  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front/app:/app
      - node_modules:/app/node_modules
    command: sh -c "yarn && PORT=3001 yarn start"
    ports:
      - 3001:3001

volumes:
  node_modules: null
