version: '3.9'

services:
  db:
    build:
      context: ./db/
      dockerfile: Dockerfile
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  api:
    tty: true
    depends_on:
      - db
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
    command: bash -c "rm -f tmp/pids/server.pid & bundle exec rails s -p 3000 -b '0.0.0.0'"
